import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import NextAuthSessionProvider from "@/app/auth/NextAuthSessionProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={'bg-[var(--bg-start)]'}>
          <NextAuthSessionProvider>
            {children}
          </NextAuthSessionProvider>
      </body>
    </html>
  );
}
